---
title: "Movielens"
date: '`r Sys.time()`'
output:
  html_document:
    #code_folding: hide
    number_sections: yes
    toc: yes
    toc_depth: 3
---

```{r setup, include=FALSE}
library(scales)
library(tidyverse)
library(knitr)

# set plot theme
theme_set(theme_bw())
```

# Load and preview data

Read data from the `ratings.csv` file
```{r load-data}
ratings <- read_csv('ratings.csv',
                    col_names = c('user_id','movie_id','rating','timestamp'))
```

Loaded `r format(object.size(ratings), units="Mb")` of ratings data, containing `r format(nrow(ratings), big.mark = ",")` ratings. Here's a preview:
```{r preview-data}
head(ratings) %>% kable()
```

# Summary statistics

```{r dist-ratings}
# plot the distribution of rating values (slide 21)
ggplot(ratings, aes(x= rating)) +
geom_histogram(bins = 10) +
scale_y_continuous(label = comma) 
```


## Per-movie stats

```{r aggregate-by-movie}
# aggregate ratings by movie, computing mean and number of ratings
# hint: use the n() function for easy counting within a group
group_by(ratings, movie_id) %>% summarize(avg = mean(rating), count = n())

  
```

```{r dist-movie-popularity}
# plot distribution of movie popularity (= number of ratings the movie received)
# hint: try scale_x_log10() for a logarithmic x axis
group_by(ratings, movie_id) %>% summarize(movie_pop=n()) %>%
ggplot(aes(x= movie_pop)) +
geom_histogram() +
scale_x_log10() +
scale_y_continuous(label = comma) +
xlab("Movie Popularity")
```

```{r dist-mean-ratings-by-movie}
# plot distribution of mean ratings by movie (slide 23)
# hint: try geom_histogram and geom_density
group_by(ratings, movie_id) %>% summarize(avg = mean(rating)) %>%
ggplot(aes(x = avg)) +
  geom_density(fill = "grey")+
  xlab("Average Movie Rating")
```

```{r cdf-movie-pop}
# rank movies by popularity and compute the cdf, or fraction of movies covered by the top-k moves (slide 25)
# hint: use dplyr's rank and arrange functions, and the base R sum and cumsum functions
# store the result in a new data frame so you can use it in creating figure 2 from the paper below
movie_rank <- group_by(ratings, movie_id) %>% summarize(count = n()) %>% arrange(desc(count)) %>% 
mutate(rank = row_number(), cdf = cumsum(count)/sum(count)) 
# plot the CDF of movie popularity
ggplot(movie_rank, aes(x = rank, y = cdf)) +
  geom_point() +
  scale_y_continuous(label = percent)
```


# Per-user stats

```{r aggregate-by-user}
# aggregate ratings by user, computing mean and number of ratings
group_by(ratings, user_id) %>% summarize(avg = mean(rating), NumRatings = n())
```

```{r dist-user-activity}
# plot distribution of user activity (= number of ratings the user made)
# hint: try a log scale here
group_by(ratings, user_id) %>% summarize(numRatings = n()) %>% 
  ggplot(aes(x = numRatings)) +
  geom_histogram() +
  scale_x_log10() +
  xlab("User Activity")
```

# Anatomy of the long tail

```{r long-tail}
# generate the equivalent of figure 2 of this paper:
# https://5harad.com/papers/long_tail.pdf

# Specifically, for the subset of users who rated at least 10 movies,
# produce a plot that shows the fraction of users satisfied (vertical
# axis) as a function of inventory size (horizontal axis). We will
# define "satisfied" as follows: an individual user is satisfied p% of
# the time at inventory of size k if at least p% of the movies they
# rated are contained in the top k most popular movies. As in the
# paper, produce one curve for the 100% user satisfaction level and
# another for 90%---do not, however, bother implementing the null
# model (shown in the dashed lines).
qualified_users <- group_by(ratings, user_id) %>% filter(n() > 10) 

movie_rank <- group_by(qualified_users, movie_id) %>% summarize(count = n()) %>% arrange(desc(count)) %>% mutate(rank = row_number())

percentiles <- left_join(qualified_users, movie_rank) %>% group_by(user_id) %>% summarise(max = max(rank), `90perc` = quantile(rank,.9))

`100P` <- select(percentiles, user_id, max) %>% group_by(max) %>% summarize(numUsers = n()) %>% arrange(max) %>% mutate(fracUsers100 = cumsum(numUsers)/ sum(numUsers))

`90P` <- select(percentiles, user_id, `90perc`) %>% group_by(`90perc`) %>% summarize(numUsers = n()) %>% arrange(`90perc`) %>% mutate(fracUsers90 = cumsum(numUsers)/ sum(numUsers))

full_join(`100P`, `90P`, by = c('max' = '90perc')) %>% select(max, fracUsers90, fracUsers100) %>% gather("table", "fracUsers", fracUsers90, fracUsers100) %>%
  ggplot(aes(x = max, y = fracUsers, color = table)) + 
  geom_smooth() +
  xlab("Inventory Size") +
  ylab("Percent of Users Satisfied")
```
